import './globals.css';
import './content.css';
import Navbar from '@/components/Navbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar brand="LMC Engineering Front"/>
        <main className="main-content">
          {children}
        </main>
      </body>
    </html>
  )
}
